apiVersion: v1
kind: Service
metadata:
  name: miappdevops-service
spec:
  type: NodePort
  selector:
    app: miappdevops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080