apiVersion: v1
kind: Service
metadata:
  name: miappdevops-metrics
  labels:
    app: miappdevops
spec:
  selector:
    app: miappdevops
  ports:
  - name: metrics
    port: 5000
    targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: miappdevops-monitor
  labels:
    app: miappdevops
    release: prometheus
spec:
  selector:
    matchLabels:
      app: miappdevops
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
